/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.userinterface;

import com.example.managerproduct.Menu;
import com.example.managerproduct.Table;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author pumba
 */
public class MenuInterface extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Data data;
    private byte menuID = 0;
    private String tableName = "No.01";
    private String productName;
    private SelectProduct selectProduct;
    private AddProduct addProduct;
    private ModifyProduct modifyProduct;

    public Data getData() {
        return data;
    }

    public void productTable(String tableName, String productName, int productQuantity) {
        data.addProductTable(tableName, productName, productQuantity);
    }

    private void setButtonProduct() {
        jButtonProduct1.setText(data.getProduct().getAlName().get(0));
        jButtonProduct2.setText(data.getProduct().getAlName().get(1));
        jButtonProduct3.setText(data.getProduct().getAlName().get(2));
        jButtonProduct4.setText(data.getProduct().getAlName().get(3));
        jButtonProduct5.setText(data.getProduct().getAlName().get(4));
        jButtonProduct6.setText(data.getProduct().getAlName().get(5));
    }

    public MenuInterface() {
        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel(Table.ID_TABLE);
        jComboBox1.setModel(model);
        data = new Data();
        setButtonProduct();
        SelectMenu(menuID);
    }

    public void SelectMenu(byte menuID) {
        switch (menuID) {
            case 0:
                break;
            case 1:
                MenuNo1();
                break;
            case 2:
                MenuNo2();
                break;
            case 3:
                MenuNo1();
                break;
            case 4:
                MenuNo3();
                break;
        }
    }

    private void MenuNo1() {
        showTextArea(menuID);
    }

    private void MenuNo2() {

    }

    private void MenuNo3() {
        showTextArea(menuID);
    }

    private void showTextArea(byte menuID) {
        switch (menuID) {
            case 0:
                break;
            case 1:
                data.showProduct(jTextAreaMenu1, menuID, tableName);
                break;
            case 2:
                break;
            case 3:
                data.showProduct(jTextAreaMenu1, menuID, tableName);
                break;
            case 4:
                data.showProduct(jTextAreaMenu2, menuID, tableName);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMenu1 = new javax.swing.JTextArea();
        jButtonPayments = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonMenuNo1 = new javax.swing.JButton();
        jButtonMenuNo2 = new javax.swing.JButton();
        jButtonMenuNo3 = new javax.swing.JButton();
        jButtonMenuNo4 = new javax.swing.JButton();
        jButtonMenuNo5 = new javax.swing.JButton();
        jPanelMenu2 = new javax.swing.JPanel();
        jButtonProduct1 = new javax.swing.JButton();
        jButtonProduct4 = new javax.swing.JButton();
        jButtonProduct2 = new javax.swing.JButton();
        jButtonProduct5 = new javax.swing.JButton();
        jButtonProduct3 = new javax.swing.JButton();
        jButtonProduct6 = new javax.swing.JButton();
        jPanelMenu3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMenu2 = new javax.swing.JTextArea();
        jButtonAddProduct = new javax.swing.JButton();
        jButtonModifyProduct = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenu1.setBorder(new javax.swing.border.MatteBorder(null));

        jTextAreaMenu1.setColumns(20);
        jTextAreaMenu1.setLineWrap(true);
        jTextAreaMenu1.setRows(5);
        jTextAreaMenu1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaMenu1);

        jButtonPayments.setText("Payments");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Please select table:");

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPayments)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButtonPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonMenuNo1.setText("1. Payments");
        jButtonMenuNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo1ActionPerformed(evt);
            }
        });

        jButtonMenuNo2.setText("2. Select product");

        jButtonMenuNo3.setText("3. Checking product\nin store");
        jButtonMenuNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo3ActionPerformed(evt);
            }
        });

        jButtonMenuNo4.setText("4. Modify product");
        jButtonMenuNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo4ActionPerformed(evt);
            }
        });

        jButtonMenuNo5.setText("5. Total revenue");

        jPanelMenu2.setBorder(new javax.swing.border.MatteBorder(null));

        jButtonProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduct1ActionPerformed(evt);
            }
        });

        jButtonProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduct4ActionPerformed(evt);
            }
        });

        jButtonProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduct2ActionPerformed(evt);
            }
        });

        jButtonProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduct5ActionPerformed(evt);
            }
        });

        jButtonProduct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduct3ActionPerformed(evt);
            }
        });

        jButtonProduct6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduct6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenu2Layout = new javax.swing.GroupLayout(jPanelMenu2);
        jPanelMenu2.setLayout(jPanelMenu2Layout);
        jPanelMenu2Layout.setHorizontalGroup(
            jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButtonProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProduct2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProduct6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenu2Layout.setVerticalGroup(
            jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProduct2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelMenu3.setBorder(new javax.swing.border.MatteBorder(null));

        jTextAreaMenu2.setColumns(20);
        jTextAreaMenu2.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMenu2);

        jButtonAddProduct.setText("Add Product");
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButtonModifyProduct.setText("Modify Product");
        jButtonModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenu3Layout = new javax.swing.GroupLayout(jPanelMenu3);
        jPanelMenu3.setLayout(jPanelMenu3Layout);
        jPanelMenu3Layout.setHorizontalGroup(
            jPanelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanelMenu3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonModifyProduct)
                .addGap(32, 32, 32))
        );
        jPanelMenu3Layout.setVerticalGroup(
            jPanelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMenuNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMenuNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMenuNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMenuNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMenuNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonMenuNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jPanelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jPanelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addComponent(jSeparator1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo1ActionPerformed
        if (!(menuID == 1)) {
            menuID = 1;
            SelectMenu(menuID);
        }
    }//GEN-LAST:event_jButtonMenuNo1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jTextAreaMenu1.setText("");
            tableName = evt.getItem().toString();
            SelectMenu(menuID);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButtonMenuNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo3ActionPerformed
        if (!(menuID == 3)) {
            menuID = 3;
            SelectMenu(menuID);

        }
    }//GEN-LAST:event_jButtonMenuNo3ActionPerformed

    private void jButtonProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduct1ActionPerformed
        SelectProduct(evt);
    }//GEN-LAST:event_jButtonProduct1ActionPerformed

    private void jButtonProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduct2ActionPerformed
        SelectProduct(evt);
    }//GEN-LAST:event_jButtonProduct2ActionPerformed

    private void jButtonProduct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduct3ActionPerformed
        SelectProduct(evt);
    }//GEN-LAST:event_jButtonProduct3ActionPerformed

    private void jButtonProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduct4ActionPerformed
        SelectProduct(evt);
    }//GEN-LAST:event_jButtonProduct4ActionPerformed

    private void jButtonProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduct5ActionPerformed
        SelectProduct(evt);
    }//GEN-LAST:event_jButtonProduct5ActionPerformed

    private void jButtonProduct6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduct6ActionPerformed
        SelectProduct(evt);
    }//GEN-LAST:event_jButtonProduct6ActionPerformed

    private void jButtonMenuNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo4ActionPerformed
        if (!(menuID == 4)) {
            menuID = 4;
            SelectMenu(menuID);
        }
    }//GEN-LAST:event_jButtonMenuNo4ActionPerformed

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        AddProduct addProduct = new AddProduct(this);
        addProduct.setVisible(true);
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    private void jButtonModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyProductActionPerformed
        modifyProduct = new ModifyProduct(this);
        modifyProduct.setVisible(true);
    }//GEN-LAST:event_jButtonModifyProductActionPerformed

    private void SelectProduct(java.awt.event.ActionEvent evt) {
        JButton button = (JButton) evt.getSource();
        productName = button.getText();
        selectProduct = new SelectProduct(this, productName);
        selectProduct.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonMenuNo1;
    private javax.swing.JButton jButtonMenuNo2;
    private javax.swing.JButton jButtonMenuNo3;
    private javax.swing.JButton jButtonMenuNo4;
    private javax.swing.JButton jButtonMenuNo5;
    private javax.swing.JButton jButtonModifyProduct;
    private javax.swing.JButton jButtonPayments;
    private javax.swing.JButton jButtonProduct1;
    private javax.swing.JButton jButtonProduct2;
    private javax.swing.JButton jButtonProduct3;
    private javax.swing.JButton jButtonProduct4;
    private javax.swing.JButton jButtonProduct5;
    private javax.swing.JButton jButtonProduct6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelMenu2;
    private javax.swing.JPanel jPanelMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaMenu1;
    private javax.swing.JTextArea jTextAreaMenu2;
    // End of variables declaration//GEN-END:variables

}
