/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.userinterface;

import com.example.managerproduct.Menu;
import com.example.managerproduct.Table;
import java.awt.event.ItemEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author pumba
 */
public class MenuInterface extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Data data;
    private byte menuID = 0;
    private String tableName = "No.01";
    private String productName;
    private SelectProduct selectProduct;
    private AddProduct addProduct;
    private ModifyProduct modifyProduct;
    private MenuNo1 menuNo1;
    private MenuNo2 menuNo2;
    private MenuNo3 menuNo3;
    public Data getData() {
        return data;
    }

    public void productTable(String tableName, String productName, int productQuantity) {
        data.addProductTable(tableName, productName, productQuantity);
    }

    private void firstSet(){
        menuNo1 = new MenuNo1(this);
        menuNo2 = new MenuNo2(this);
        menuNo3 = new MenuNo3(this);
        dpMenuMain.add(menuNo1);
        dpMenuMain.add(menuNo2);
        dpMenuMain.add(menuNo3);
        
    }
    
    public MenuInterface() {
        initComponents();
        data = new Data();
        firstSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonMenuNo1 = new javax.swing.JButton();
        jButtonMenuNo2 = new javax.swing.JButton();
        jButtonMenuNo3 = new javax.swing.JButton();
        jButtonMenuNo4 = new javax.swing.JButton();
        jButtonMenuNo5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        dpMenuMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManagerProduct");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jButtonMenuNo1.setText("1. Payments");
        jButtonMenuNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo1ActionPerformed(evt);
            }
        });

        jButtonMenuNo2.setText("2. Select product");
        jButtonMenuNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo2ActionPerformed(evt);
            }
        });

        jButtonMenuNo3.setText("3. Checking product\nin store");
        jButtonMenuNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo3ActionPerformed(evt);
            }
        });

        jButtonMenuNo4.setText("4. Modify product");
        jButtonMenuNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuNo4ActionPerformed(evt);
            }
        });

        jButtonMenuNo5.setText("5. Total revenue");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout dpMenuMainLayout = new javax.swing.GroupLayout(dpMenuMain);
        dpMenuMain.setLayout(dpMenuMainLayout);
        dpMenuMainLayout.setHorizontalGroup(
            dpMenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        dpMenuMainLayout.setVerticalGroup(
            dpMenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMenuNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenuNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpMenuMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonMenuNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMenuNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMenuNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonMenuNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonMenuNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpMenuMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo1ActionPerformed
        hideInteralFrame();
        menuNo1.show();
        menuNo1.showMenu();
        if (menuID != 1){
            menuID = 1;
            menuNo1.showTextArea(menuID);
        }
    }//GEN-LAST:event_jButtonMenuNo1ActionPerformed

    private void jButtonMenuNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo3ActionPerformed
        hideInteralFrame();
        menuNo1.show();
        menuNo1.hideMenu();
        if (menuID != 3){
            menuID = 3;
            menuNo1.showTextArea(menuID);
        }
    }//GEN-LAST:event_jButtonMenuNo3ActionPerformed

    private void jButtonMenuNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo4ActionPerformed
        hideInteralFrame();
        menuNo3.show();
    }//GEN-LAST:event_jButtonMenuNo4ActionPerformed

    private void jButtonMenuNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuNo2ActionPerformed
        hideInteralFrame();
        menuNo2.show();
    }//GEN-LAST:event_jButtonMenuNo2ActionPerformed

    private void hideInteralFrame(){
        menuNo1.hide();
        menuNo2.hide();
        menuNo3.hide();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMenuMain;
    private javax.swing.JButton jButtonMenuNo1;
    private javax.swing.JButton jButtonMenuNo2;
    private javax.swing.JButton jButtonMenuNo3;
    private javax.swing.JButton jButtonMenuNo4;
    private javax.swing.JButton jButtonMenuNo5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
