/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.userinterface;

import java.awt.event.ActionEvent;
import javax.swing.JButton;

/**
 *
 * @author pumba
 */
public class MenuNo2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuNo2
     */
    
    MenuInterface menuInterface;
    SelectProduct selectProduct;
    String productName;
    int productPrice;
    int productQuantity;
    
    public MenuNo2(MenuInterface menuInterface) {
        initComponents();
        this.menuInterface = menuInterface;
        setBTSelectProduct();
    }
    
    private void setBTSelectProduct(){
//        for (int i =0; i < menuInterface.getData().getProduct().getHsQuantity().size(); i++){
        btProduct1.setText(menuInterface.getData().getProduct().getAlName().get(0));
        btProduct2.setText(menuInterface.getData().getProduct().getAlName().get(1));
        btProduct3.setText(menuInterface.getData().getProduct().getAlName().get(2));
        btProduct4.setText(menuInterface.getData().getProduct().getAlName().get(3));
        btProduct5.setText(menuInterface.getData().getProduct().getAlName().get(4));
        btProduct6.setText(menuInterface.getData().getProduct().getAlName().get(5));
//        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btProduct1 = new javax.swing.JButton();
        btProduct2 = new javax.swing.JButton();
        btProduct3 = new javax.swing.JButton();
        btProduct4 = new javax.swing.JButton();
        btProduct5 = new javax.swing.JButton();
        btProduct6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Select Product");
        setPreferredSize(new java.awt.Dimension(500, 400));

        btProduct1.setText("jButton1");
        btProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduct1ActionPerformed(evt);
            }
        });

        btProduct2.setText("jButton2");
        btProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduct2ActionPerformed(evt);
            }
        });

        btProduct3.setText("jButton3");
        btProduct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduct3ActionPerformed(evt);
            }
        });

        btProduct4.setText("jButton4");
        btProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduct4ActionPerformed(evt);
            }
        });

        btProduct5.setText("jButton5");
        btProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduct5ActionPerformed(evt);
            }
        });

        btProduct6.setText("jButton6");
        btProduct6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProduct6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btProduct2)
                        .addGap(18, 18, 18)
                        .addComponent(btProduct3))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btProduct4)
                        .addGap(18, 18, 18)
                        .addComponent(btProduct5)
                        .addGap(18, 18, 18)
                        .addComponent(btProduct6)))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btProduct1, btProduct2, btProduct3, btProduct4, btProduct5, btProduct6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProduct2)
                    .addComponent(btProduct3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProduct4)
                    .addComponent(btProduct5)
                    .addComponent(btProduct6))
                .addGap(0, 219, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btProduct1, btProduct2, btProduct3, btProduct4, btProduct5, btProduct6});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduct1ActionPerformed
        addProduct(evt);
    }//GEN-LAST:event_btProduct1ActionPerformed

    private void btProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduct2ActionPerformed
        addProduct(evt);
    }//GEN-LAST:event_btProduct2ActionPerformed

    private void btProduct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduct3ActionPerformed
        addProduct(evt);
    }//GEN-LAST:event_btProduct3ActionPerformed

    private void btProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduct4ActionPerformed
        addProduct(evt);
    }//GEN-LAST:event_btProduct4ActionPerformed

    private void btProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduct5ActionPerformed
        addProduct(evt);
    }//GEN-LAST:event_btProduct5ActionPerformed

    private void btProduct6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProduct6ActionPerformed
        addProduct(evt);
    }//GEN-LAST:event_btProduct6ActionPerformed

    private void addProduct(ActionEvent evt){
        JButton button = (JButton) evt.getSource();
        productName = button.getText();
        selectProduct = new SelectProduct(menuInterface, productName);
        selectProduct.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProduct1;
    private javax.swing.JButton btProduct2;
    private javax.swing.JButton btProduct3;
    private javax.swing.JButton btProduct4;
    private javax.swing.JButton btProduct5;
    private javax.swing.JButton btProduct6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
